version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/circleci-champaign
    docker:
      # - image: circleci/ruby:2.4.1-node
      - image: souadmin/champaign-deploy:0.0.7
        environment:
          RAILS_ENV: test
      - image: postgres:9.4.12
        environment:
          POSTGRES_USER: champaign
          POSTGRES_DB: champaign
      - image: redis

    steps:
      - checkout

      # Restore cache
      - restore_cache:
          key: champaign-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          key: champaign-{{ checksum "yarn.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: champaign-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: yarn

      - save_cache:
          key: champaign-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

     # Database setup
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # - run:
          # name: Run JS tests
          # command: yarn run test

      # - run:
          # name: Run specs
          # command: CI_NODE_TOTAL=2 CI_NODE_INDEX=0 bundle exec rake knapsack:rspec

      - deploy:
          name: Deploy to ElasticBeanstalk
          command: |
            eb init sou-champs -v -r us-west-2 -p ruby && \
            eb deploy
